#cluster:
#  zookeeper:
#    hostPort: localhost:2181
#    sessionTimeout: 100000
naming:
  jetty:
    host: localhost
    port: 10800
    context_path: /
remote:
  gRPC:
    host: localhost
    port: 11800
agent_gRPC:
  gRPC:
    host: localhost
    port: 11800
agent_jetty:
  jetty:
    host: localhost
    port: 12800
    context_path: /
agent_stream:
  default:
    buffer_file_path: ../buffer/
    buffer_offset_max_file_size: 10M
    buffer_segment_max_file_size: 500M
ui:
  jetty:
    host: localhost
    port: 12800
    context_path: /
storage:
#  elasticsearch:
#    cluster_name: CollectorDBCluster
#    cluster_transport_sniffer: true
#    cluster_nodes: localhost:9300
#    index_shards_number: 2
#    index_replicas_number: 0
  shardingjdbc:
    url_0: jdbc:mysql://10.7.8.174:13306/collector
    username_0: admin
    password_0: "123456"
    url_1: jdbc:mysql://10.7.8.175:13306/collector
    username_1: admin
    password_1: "123456"
    url_2: jdbc:mysql://10.4.14.131:13306/collector
    username_2: admin
    password_2: "123456"
    url_3: jdbc:mysql://10.4.14.132:13306/collector
    username_3: admin
    password_3: "123456"